Add TZ env variables to all backend services
iver-wharf/wharf-docker-compose pull request #9
Opened 2021-08-17 16:29 UTC by fredx30

This is the implementation of all the tzdata package i recently added to all the backend services in the following PRs:

https://github.com/iver-wharf/wharf-provider-github/pull/25
https://github.com/iver-wharf/wharf-provider-azuredevops/pull/20
https://github.com/iver-wharf/wharf-provider-gitlab/pull/20
https://github.com/iver-wharf/wharf-api/pull/40

2021-08-18 10:02 UTC, jilleJr approved these changes
A nitpick, but LGTM!

2021-08-18 10:02 UTC, applejag commented on docker-compose.yml
>        POSTGRES_PASSWORD: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
nit: Interesting mix of different environment variable syntaxes here. Could you change to only use the map/object syntax instead for all services, if that doesn't collide too much with the other PRs you have up?

Something we've done in other projects is to abuse YAML anchors and references to deduplicate some of these global settings. Such as:

```yaml
x-env-timezone: &x-env-timezone
  TZ: Europe/Stockholm

services:
  web:
    environment:
      <<: *x-env-timezone

  api:
    environment:
      <<: *x-env-timezone
```

![Screenshot from 2021-08-18 11-57-30](https://user-images.githubusercontent.com/2477952/129878825-e771dc19-8a63-4915-adf7-416b1758b1f5.png)

(Top-level fields starting with `x-` are ignored by Docker Compose, allowing for such anchoring)

This does not work with lists, so I find it better to store environments as maps instead of lists

2021-08-19 05:36 UTC, Alexamakans approved these changes

2021-08-26 10:39 UTC, applejag approved these changes

2021-08-27 16:15 UTC, fredx30 commented on docker-compose.yml
>        POSTGRES_PASSWORD: OL2AEn6lgj6ekajgKJIOanefgegnksngpoetPIEQjhankf7412
@jilleJr this now does alot more. I though the dedupe just added more lines as you described so i included a few more attributes and renamed it. 
There was then subsequently an issue with mapping to true/false type values. These ("Yes", "true", "TRUE") have now been turned into quoted strings which i expect to function as before.

2021-08-30 05:53 UTC, jilleJr requested changes

2021-08-30 05:53 UTC, jilleJr commented on docker-compose.yml
> +#    image: quay.io/iver-wharf/wharf-web
wharf-web is disabled in the docker-compose.build.yml. In this file, wharf-web needs to be enabled so it's easy to spin up a local instance of Wharf without needing any other repos than wharf-docker-compose

```suggestion
  web:
    image: quay.io/iver-wharf/wharf-web
```

2021-08-30 05:53 UTC, jilleJr commented on docker-compose.yml
> +      RABBITMQDISABLESSL: "TRUE"
nit: While you have tampered with these, could you make this "TRUE" lowercase for consistency? I am sure that the case does not matter when it is parsed.

```suggestion
      RABBITMQDISABLESSL: "true"
```

2021-08-30 08:08 UTC, jilleJr approved these changes
LGTM!

2021-08-30 08:16 UTC, fredx30 commented
Requires a merge of https://github.com/iver-wharf/wharf-provider-azuredevops/pull/20 prior to merging this.

2021-08-30 08:55 UTC, merged